vim.keymap.set("n", "<Leader>ex", "<cmd>Ex<CR>", { desc = "Open netrw"})
vim.keymap.set("n", "<Esc>", function()
  vim.cmd("nohlsearch")
end)
vim.keymap.set("n", "n", "nzzzv")
vim.keymap.set("n", "N", "Nzzzv")
vim.keymap.set("n", "<Leader>d", "\"_d", { desc = "Delete to Void"})
vim.keymap.set("v", "<Leader>d", "\"_d", { desc = "Delete to Void"})
